### ISSUE TITLE
Weekly Report 5

### ISSUE THREAD

**Issue by rachit-bhatt** [rachit-bhatt/Capstone-Project#7]
Document the progress in week 5.

**Comment by SakshiOberoi786** [comment]
[WeeklyProgressReport-GroupB-Week5.docx](https://github.com/user-attachments/files/17271031/WeeklyProgressReport-GroupB-Week5.docx)
Rachit, Can You please take care of git hub charts as Theoretical part is done?

**Comment by rachit-bhatt** [comment]
Sure thing! Great work, @SakshiOberoi786!

Although GitHub charts are not under my control, it is a reflective mirror of our contributions to the project in the respected springs ♨️ and milestones.

The charts that we use in our reports would be accessible at **Insights** in menu.

Let me know if it is not visible to you.

**Comment by rachit-bhatt** [comment]
I hope you will be done with that soon.

Waiting for your PR. 🤞🏻

**Comment by rachit-bhatt** [comment]
PR - https://github.com/rachit-bhatt/Capstone-Project/pull/40
